### ISSUE TITLE
FLOTIQ: Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by lefeuilleter** [flotiq/flotiq-blog#36]
When i start development server initially right after installation instructions everything seems fine, but when i stop dev server and then restart dev server i get this error 

FLOTIQ: Cannot read property 'type' of undefined

If i run gatsby clean, and then try again dev server starts without errors, but only until i stop it. Then if i start it again, i get the same error.

### To Reproduce

1. run gatsby develop
2. stop dev server
3. run gatsby develop again

* Gatsby Version: 4.6.0
* Node Version: v14.17.5
* OS: Windows 10

![screenshot](https://user-images.githubusercontent.com/95861949/154528426-c672c24c-5eb3-421d-be3c-6488ec3dd464.PNG)

**Comment by CiotkaCierpienia** [comment]
Hi,
We are aware of that problem, sorry we didn't communicate it. The fast fix is adding `forceReload: true,` to the `'gatsby-source-flotiq'` plugin config in the `gatsby-config.js` file. I will let you know when we will resolve the problem in the plugin.

**Comment by lefeuilleter** [comment]
> Hi, We are aware of that problem, sorry we didn't communicate it. The fast fix is adding `forceReload: true,` to the `'gatsby-source-flotiq'` plugin config in the `gatsby-config.js` file. I will let you know when we will resolve the problem in the plugin.

Hi! Thanks for reply! I checked, and `forceReload: true` is already in `'gatsby-source-flotiq' ` options. But i still get the same error.

**Comment by CiotkaCierpienia** [comment]
Hi,
We've fixed the source plugin, so after pull and install the problem should disappear.
